APP_CONFIG = {
	autoCompleteSources: {
		to: [
			'window',
			'.container-box',
			'.navbar',
			'ul li',
			'p',
			'.content-head',
			'.pure-u-1-2',
			'input',
			'button',
			'pre',
			'#welcome',
			'#tryit',
			'.splash-head',
			'.splash-subhead',
			'l-box-lrg',
			'.content-subhead'
		],
		if: [
			'click',
			'dblclick',
			'mousedown',
			'mouseenter',
			'mouseleave',
			'mouseover',
			'mouseup',
			'scroll',
			'resize',
			'focus',
			'change',
			'contextmenu',
			'keypress',
			'animationend',
			'orientationchange'
		],
		to: [

		],
		do: [
          'bounce',
          'flash',
          'pulse',
          'rubberBand',
          'shake',
          'swing',
          'tada',
          'wobble',
          'bounceIn',
          'bounceInLeft',
          'bounceInRight',
          'bounceOut',
          'bounceOutDown',
          'bounceOutUp',
          'fadeIn',
          'fadeInLeftBig',
          'fadeInUpBig',
          'fadeOut',
          'fadeOutDown',
          'fadeOutRight',
          'flip',
          'flipInX',
          'flipOutY',
          'lightSpeedIn',
          'rotateIn',
          'rotateInDownRight',
          'rotateInUpRight',
          'rotateOut',
          'rotateOutDownRight',
          'rotateOutUpRight',
          'slideInDown',
          'slideOutRight',
          'slideOutUp',
          'hinge',
          'rollIn',
          'rollOut'

		]
	} 
}